name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # 执行步骤
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Test SSH connection
        run: ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} 'echo "SSH connection successful"'
      - name: Deploy to HelloWord Service
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          cd ~/website/Platform
            git reset --hard
            git pull
            pnpm install
            pnpm run build
            pm2 restart platform || pm2 start yarn -n "platform" --cwd /home/helloworld/website/Platform/ -- run start
            cd server/node
            pnpm install
            npx prisma generate
            npx prisma db pull
            pm2 restart platform-server || pm2 start yarn -n "platform-server" --cwd /home/helloworld/website/Platform/server/node -- run start 
          EOF
